name: HideThePlayer
version: '${project.version}'
main: me.kekschen.hidetheplayer.HideThePlayer
api-version: 1.17
depend:
  - ProtocolLib
commands:
  hidetheplayer:
    permission: rwm.hidetheplayer
    usage: /hidetheplayer
    aliases: htp